server:
  port: 12003

spring:
  profiles:
    active: local
  application:
    name: health-server

  boot:
    admin:
      ui:
        title: "应用健康监控"
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>${spring.boot.admin.ui.title}</span>
        view-settings:
          - name: "about"
            enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}