server:
  port: 18888
  servlet:
    context-path: /swagger

knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routeAuth:
      enable: true
      username: api
      password: api@123
    routes:
      - name: 系统管理服务
        uri: wudgaby.com:12306/api/sys
        location: /v2/api-docs?group=综合管理
      - name: 工作流服务
        uri: wudgaby.com:12306/api/flow
        location: /v2/api-docs?group=工作流
