spring:
  application:
    name: mail-spring-boot-demo
    
  mail:
    host: smtp.qq.com
    username: 523679498@qq.com
    password: ttqopqgnchsobjab
    properties.mail.smtp.auth: true
    properties.mail.starttls.enable: true
    properties.mail.starttls.required: true
    test-connection: false