server:
  port: 18081
  servlet:
    context-path: /flowable

spring:
  application:
    name: flowable-module-integration
  datasource:
    url: jdbc:mysql://192.168.199.151:3306/caseoa?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: Abc123,./
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      maxActive: 30
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: 127.0.0.1,localhost
        #deny:

mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  config-location: classpath:/META-INF/mybatis-config.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

flowable:
  common:
    app:
      idm-url: http://wudgaby.com:18081/flowable
