spring:
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    # Redis默认情况下有16个分片，这里配置具体使用的分片。默认是索引为0的分片
    database: 0

    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 60s
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 2