server:
  port: 9923
  ssl:
    enabled: true
    key-store: classpath:server.keystore
    key-alias: tomcat
    key-store-password: 123456
    key-store-type: JKS

sso:
  app-code: app3
  app-key: zfdREleBvl
  app-secret: TzdeKIJwlLitqAumpKinhIovvdvyFP
  #target-url: http://app3.com:${server.port}