server:
  port: 9922
  ssl:
    enabled: true
    key-store: classpath:server.keystore
    key-alias: tomcat
    key-store-password: 123456
    key-store-type: JKS

sso:
  app-code: app2
  app-key: bMqAImeeov
  app-secret: zpzqqlVJeajWlxZaxEMQIzlZRsQCzd
  #target-url: http://app2.com:${server.port}