spring:
  application:
    name: sso-web-client
  http:
    encoding:
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: false
  thymeleaf:
    cache: false
  profiles:
    active: appA

logging:
  config: classpath:logback-spring.xml

sso:
  logout-path: /sso/logout
  server: http://localhost:9900