spring:
  application:
    name: redis-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    password: redis-pwd
    alone-list:
      write:
        database: 1
        host: 127.0.0.1
        port: 6379
        timeout: 10s
        lettuce:
          pool:
            maxActive: 2
      read:
        database: 2
        host: 127.0.0.1
        port: 6379
        timeout: 10s
        lettuce:
          pool:
            maxActive: 2
