server:
  port: 12540

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

sms:
  app-id: 1400168812
  app-key: 82f16ac557da5cce8a26816a7b485fd0
  sign: 安络科技

alarm:
  dd-webhook: https://oapi.dingtalk.com/robot/send?access_token=4ae0756d9a933aea542a906593310e9396f2ad22cf9777444e8c16b2d82852ff
  send-mail: false
  sendTo:
    - non-existent@cnns.com

#极光账号
jpush:
  app-key: 9ee1309cd2110d5d006d8d25
  app-secure: 830e9ddf56873a31b850b11f

#阿里账号
ali:
  accessKeyId: LTAIRJ3Ab3nLv0Hw
  accessKeySecret: yGdTOazedeJY1fsv7cmjxVQvFfP6B4

#阿里推送
ali-push:
  app-key: 29128818
  app-secure: 727805900aa933db4df931e46a18f7f7
  #ios才有
  apns-env: DEV