spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tenant_test?serverTimezone=GMT%2B8
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.wudgaby.sample.domain
  configuration:
    #日志输出 2选1配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-helper:
  demo-env: true
  exclude-urls:
    - /sysTenants/**
    - /sysUsers/**

tenant:
  enable: true
  ignore-tables:
    - sys_config
    - sys_tenant
  ignore-urls:
    - /sysUsers/login
    - /doc.html
  type: aspect
