server:
  ssl:
    enabled: true
    key-store-password: 123456
    key-alias: server
    key-store: classpath:server.p12
    key-store-type: pkcs12

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wudgaby_sys?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

upload:
   path: D:\\upload

demoEnv: true