server:
  port: 8010
  shutdown: GRACEFUL
  tomcat:
    threads:
      max: 500
    accept-count: 1000

spring:
  profiles:
    active: @profile.active@
  application:
    name: admin-sys
  lifecycle:
    timeout-per-shutdown-phase: 30S

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.wudgaby.platform.sys.entity
  type-enums-package: com.wudgaby.platform.sys.enums
  configuration:
    #日志输出 2选1配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #tablePrefix: poe
      insert-strategy: not_null
      update-strategy: not_null
      #select-strategy: default
      id-type: assign_id
      table-underline: true
      #全局逻辑删除字段值
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

repeatsubmit:
  enabled: false

swagger:
  enabled: true

knife4j:
  production: false
  basic:
    enable: false
    username: swagger
    password: swagger