drop table `user` if exists;
create table `user`(id bigint generated by default as identity,
                    username varchar(20),
                    password varchar(50),
                    `name` varchar(20),
                    phone varchar(20),
                    email varchar(50),
                    primary key(id));