spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          rocketmq:
            bindings:
              resource-output:
                producer:
                  group: api-producer-group
                  sync: false
      bindings:
        resource-output:
          destination: api-register-topic
          content-type: application/json

        resource-input:
          destination: api-register-topic
          content-type: application/json
          group: api-consumer-group