spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_auth?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.wudgaby.platform.data.auth.entity
  type-enums-package: com.wudgaby.platform.data.auth.enums

  global-config:
    db-config:
      #tablePrefix: poe
      insert-strategy: not_null
      update-strategy: not_null
      #select-strategy: default
      id-type: assign_id
      table-underline: true
      #全局逻辑删除字段值
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0