server:
  port: 12540

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  dinger:
    project-id: ${spring.application.name}
    dingers:
      # 使用钉钉机器人, 请根据自己机器人配置信息进行修改
      dingtalk:
        token-id: xx
        secret: xx

sms:
  app-id: xx
  app-key: xx
  sign: xx

alarm:
  send-mail: false
  sendTo:
    - non-existent@domain.com

#极光账号
jpush:
  app-key: xx
  app-secure: xx

#阿里账号
ali:
  accessKeyId: xx
  accessKeySecret: xx

#阿里推送
ali-push:
  app-key: xx
  app-secure: xx
  #ios才有
  apns-env: DEV