server:
  port: 9910

spring:
  application:
    name: sso-token-client
  http:
    encoding:
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: false
  redis:
    host: localhost
    port: 6379
    password: redis-pwd

logging:
  config: classpath:logback-spring.xml

sso:
  logout-path: /sso/logout
  server: http://localhost:9900
  app-code: app1
  app-key: QZkstbHXhM
  app-secret: UpIHyEcvoRQXGfBNipVnQzvdhodgvs
  #target-url: http://app1.com:${server.port}