server:
  port: 8022

spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            provider: gitee
            client-id: 835d9350cfa260df1d3db67ec3158ce99cea90340537e8a3d0229affc05fb0ee
            client-secret: c0dac0a90dda1d5cd0c2315140d6cccce787aa5df9d7aaecc0638a5f70aa2004
            authorization-grant-type: authorization_code
            #redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri: '{baseScheme}://wugg.com{basePort}{basePath}/login/oauth2/code/{registrationId}'
            scope: user_info
            client-name: Gitee
            client-alias: gitee
          github:
            provider: github
            client-id: Iv1.29b3406f72bdb777
            client-secret: 8dbf7d7549660dbc57579b797a0792e8fb2af120
            authorization-grant-type: authorization_code
            redirect-uri: '{baseScheme}://wugg.com{basePort}{basePath}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: id

  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:~/h2/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:sql/init.sql
      data-locations: classpath:sql/data.sql

  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
