spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wudgaby_sys?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: root
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      suffix: .html
      prefix: /

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.wudgaby.sample.data.sensitive.entity
  type-enums-package: com.wudgaby.sample.data.sensitive.enums
  configuration:
    #日志输出 2选1配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #tablePrefix: poe
      insert-strategy: not_null
      update-strategy: not_null
      #select-strategy: default
      id-type: auto
      table-underline: true
      #全局逻辑删除字段值
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

swagger:
  enabled: true

knife4j:
  production: false
  basic:
    enable: false
    username: swagger
    password: swagger

resubmit:
  enabled: false

crypto:
  data:
    db-crypto: true
    db-dict-bind: true