server:
  port: 8686

spring:
  application:
    name: code-generator
  datasource:  #改数据库配置
    url: jdbc:mysql://localhost:3306/wudgaby_sys?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: ALWAYS

codegen:
  enabled: true


