crypto:
  data:
    key: qwertyuiop!@#$%^
    simple: true
    db-crypto: true
    db-dict-bind: false
    custom:
      mode: CBC
      padding: PKCS7Padding
      key: qwertyuiop!@#$%^
      iv: 2023070520113929
